language: node_js
node_js:
  - "7"
install: ./travis-install.sh
script: ./gulp dist && ./gulp links
notifications:
  recipients:
    - geirarne@gmail.com
    - arve.seljebu@gmail.com
env:
  - BUILD_PDF=false
