#!/bin/bash
git submodule init
git submodule update --remote --depth 1
cd codeclub_lesson_builder
npm install
if [ $? -ne 0 ]; then # try again
  echo "Setup feilet, prøver en gang til."
  # oooh, i'm nasty, but i think this will work out for us two
  rm -fr node_modules
  npm install
fi
cd ..
