* On converting documents from Word to Markdown
Just running ~pandoc -o doc.md doc.docx~ seems to work okay for pure text. How
to include images? Markdown links to external images.

- This task was originally discussed on a [[https://github.com/kodeklubben/oppgaver/issues/378][Github issue]]
- The markdown-formatted task is based on a Google Document downloaded as a DOCX
  file from a [[https://drive.google.com/drive/folders/0B8HijCRVaNkQUXFXa3dRckNmbWs][shared google drive folder]]
- [[http://pandoc.org/][Pandoc]] is used for document conversion
** Emacs terminals
- ~term~ gives vanilla Z shell
- ~shell~ allows some Emacs-style things.

~shell~ doesn't like running man pages.

~eshell~ uses an Emacs built in Man browser on ~man pandoc~. Looks good! Don't
really need ~ehsell~, thought. ~M-x man pandoc~ is sufficient. Yay!
** Pandoc manual pages
The pandoc manual contains a section on specifying ~data-directory~:

#+BEGIN_EXAMPLE
       --data-dir=DIRECTORY
              Specify  the  user  data directory to search for pandoc data files.  If this option is not specified,
              the default user data directory will be used.  This is, in Unix:
#+END_EXAMPLE

But this seems to account for /pandoc files/, not output files. What we want is
likely the ~extract-media~

#+BEGIN_EXAMPLE
       --extract-media=DIR
              Extract images and other media contained in a docx or epub container to the path DIR, creating it  if
              necessary,  and  adjust  the  images references in the document so they point to the extracted files.
              This option only affects the docx and epub readers.
#+END_EXAMPLE

Looks better. Now, let's try run this. Options come before input files, in no
specific order: ~pandoc [options] [input-file]...~.

#+BEGIN_SRC shell
pandoc -o doc.md --extract-media=media doc.docx
#+END_SRC

This seems to work fine.
** Further work
Run shell commands directly from Org mode instead. Put the output in a drawer,
and keep the shell commands /directly/ in the script that executes them.

Generalized: "separation of concerns" is a good thing, but that does not mean
"information is separate from instruction". HTML/Javascript; Org-mode/Shell.
Same concept. Challenge it!
