name: Codeclub-viewer
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Clone codeclub-viewer
        run: git clone --depth=1 --branch=master https://github.com/kodeklubben/codeclub-viewer.git ../codeclub-viewer
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build
        run: |
          cd ../codeclub-viewer
          yarn build:travis
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.MANGO }}
          publish_branch: main
          publish_dir: ../codeclub-viewer/dist
          external_repository: sagatun/sagatun.github.io
